module.exports = {
    "activation_index": "/pages/activation/index",
    "bluetooth_add_index": "/pages/bluetooth/add/index",
    "bluetooth_explain_index": "/pages/bluetooth/explain/index",
    "bluetooth_index": "/pages/bluetooth/index",
    "bluetooth_synchronization_index": "/pages/bluetooth/synchronization/index",
    "bluetooth_transfer_index": "/pages/bluetooth/transfer/index",
    "clock_index": "/pages/clock/index",
    "consult_index": "/pages/consult/index",
    "home_index": "/pages/home/index",
    "login_index": "/pages/login/index",
    "mine_index": "/pages/mine/index",
    "mine_info_index": "/pages/mine/info/index",
    "mine_introduce_index": "/pages/mine/introduce/index",
    "mine_month_index": "/pages/mine/month/index",
    "mine_programme_index": "/pages/mine/programme/index",
    "mine_report_index": "/pages/mine/report/index",
    "questionnaire_answerone_index": "/pages/questionnaire/answerone/index",
    "questionnaire_answerthree_index": "/pages/questionnaire/answerthree/index",
    "questionnaire_answertwo_index": "/pages/questionnaire/answertwo/index",
    "questionnaire_info_index": "/pages/questionnaire/info/index",
    "questionnaire_programme_index": "/pages/questionnaire/programme/index",
    "record_index": "/pages/record/index",
    "result_index": "/pages/result/index",
    "web_index": "/pages/web/index"
}